import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/ui/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const roboto = Roboto({
    subsets: ["latin"],
});

const dm_sans = DM_Sans({
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${dm_sans.className} antialiased`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
